# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_jud_date', models.DateField()),
                ('info_processing', models.TextField()),
                ('end_date', models.DateField()),
                ('arbitr_status', models.CharField(max_length=64)),
                ('arbitr_start', models.CharField(max_length=64)),
                ('list_creditors', models.TextField()),
                ('creditor_requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Arbitration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('dismissal_date', models.DateField()),
                ('organization_field', models.CharField(max_length=64)),
                ('office_location', models.CharField(max_length=64)),
                ('activity_info', models.TextField()),
                ('name_register', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_complete_date', models.DateField()),
                ('id_exam_protocol', models.CharField(max_length=8)),
                ('date_certificate_mju', models.DateField()),
                ('date_certificate', models.DateField()),
                ('info_quality', models.DateField()),
                ('full_number', models.CharField(max_length=13)),
                ('working_exp', models.IntegerField(max_length=8)),
                ('renewal_certificate', models.CharField(max_length=64)),
                ('audit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinalPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('protocol_number', models.CharField(max_length=64)),
                ('Arbitration_arbitr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Arbitration')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('certificate_arbitr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Certificate')),
            ],
        ),
        migrations.CreateModel(
            name='Jud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('judge_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exist', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('ownership_part', models.IntegerField(max_length=8)),
                ('kved', models.CharField(max_length=64)),
                ('goverment_part', models.IntegerField()),
                ('jud_procedure', models.CharField(max_length=64)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RenewalCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbitr_id', models.CharField(max_length=8)),
                ('issue_date', models.DateField()),
                ('certificate_arbitr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Certificate')),
            ],
        ),
        migrations.AddField(
            model_name='arbitration',
            name='certificate_arbitr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Certificate'),
        ),
        migrations.AddField(
            model_name='act',
            name='arbitr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Arbitration'),
        ),
        migrations.AddField(
            model_name='act',
            name='jud_id_judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Jud'),
        ),
        migrations.AddField(
            model_name='act',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
    ]
