# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160503_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='arbitr_id',
            new_name='arbitration',
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
