# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160407_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='working_exp',
            field=models.IntegerField(),
        ),
    ]
