# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160504_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitration',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
