# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160407_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='arbitr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Arbitration'),
        ),
        migrations.AlterField(
            model_name='act',
            name='arbitr_start',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='arbitr_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='creditor_requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='finish_jud_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='info_processing',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='jud_id_judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Jud'),
        ),
        migrations.AlterField(
            model_name='act',
            name='list_creditors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
        migrations.AlterField(
            model_name='act',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='activity_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='certificate_arbitr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Certificate'),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='dismissal_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='full_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='name_register',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='office_location',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='organization_field',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='audit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_certificate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_certificate_mju',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='exam_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='full_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id_exam_protocol',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='info_quality',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='renewal_certificate',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='working_exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disciplinalpenalty',
            name='Arbitration_arbitr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Arbitration'),
        ),
        migrations.AlterField(
            model_name='disciplinalpenalty',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='disciplinalpenalty',
            name='protocol_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='duplicatecertificate',
            name='certificate_arbitr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Certificate'),
        ),
        migrations.AlterField(
            model_name='duplicatecertificate',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jud',
            name='adress',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jud',
            name='judge_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='jud',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='goverment_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='jud_procedure',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='kved',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ownership_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='renewalcertificate',
            name='arbitr_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='renewalcertificate',
            name='certificate_arbitr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Certificate'),
        ),
        migrations.AlterField(
            model_name='renewalcertificate',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
