# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitration',
            name='dep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Department'),
        ),
    ]
