# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_arbitration_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default="Kyiv, Puskin's Street, Domovuskin's House, 5", max_length=64),
            preserve_default=False,
        ),
    ]
