# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_department_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='jud_id_judge',
            new_name='jud',
        ),
        migrations.AddField(
            model_name='act',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='arbitration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Arbitration'),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='activity_info',
            field=models.TextField(verbose_name='Інформація щодо діяльності'),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='dep',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Department'),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='dismissal_date',
            field=models.DateField(verbose_name='Дата звільнення'),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='name_register',
            field=models.CharField(max_length=64, verbose_name="Ім'я регістратора"),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='office_location',
            field=models.CharField(max_length=6, verbose_name='Розміщення офісу'),
        ),
        migrations.AlterField(
            model_name='arbitration',
            name='organization_field',
            field=models.CharField(max_length=64, verbose_name='Назва організації'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='audit',
            field=models.TextField(verbose_name='Аудит'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_certificate',
            field=models.DateField(verbose_name='Дата видачі сертифікату'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_certificate_mju',
            field=models.DateField(verbose_name='Дата отримання сертифікату в МЮУ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='exam_complete_date',
            field=models.DateField(verbose_name='Дата здачі екзамену'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='full_number',
            field=models.CharField(max_length=13, verbose_name='Номер сертифікату'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id_exam_protocol',
            field=models.CharField(max_length=8, verbose_name='Номер екзаменацыйного протоколу'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='info_quality',
            field=models.DateField(verbose_name='Дата отримання оцінки'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='renewal_certificate',
            field=models.CharField(max_length=64, verbose_name='Відновлення сертифікату'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='working_exp',
            field=models.IntegerField(default=0, verbose_name='Досвід роботи'),
        ),
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
