# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160510_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitration',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арбітражний керуючий'),
        ),
    ]
