# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160510_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='arbitr_start',
            field=models.DateField(),
        ),
    ]
